#!/bin/bash

export PROJECT_ID="YOUR_PROJECT_ID"
export REGION="REGION_NAME"

export REDIS_SIZE=1
export REDIS_TIER="basic"
export VPC_NETWORK="default"
export VPC_SUBNET="default"
export REDIS_IP="WILL_BE_UPDATED_AFTER_REDIS_DEPLOYMENT" 
export SCORE_THRESHOLD=0.2
export CACHE_TTL=3600
export APIGEE_ORG="$PROJECT_ID"
export APIGEE_ENV="APIGEE_ENV_NAME"
export APIGEE_HOST_NAME="APIGEE_HOST_NAME"
